{{$smarty.template}|helper:'page':'registerTemplate':'wd'}
{'CiviCRM'|helper:'page':'headline'}
<div class="row">
    <div class="col-lg-12 col-md-12">
        {$page->headline}
        {'CiviCRM'|helper:'page':'getLogo':'m':'png'}
        <p><strong>CiviCRM</strong> is a web-based, open source, internationalised suite of computer software for constituency relationship management, that falls under the broad rubric of customer relationship management. It is specifically designed for the needs of non-profit, non-governmental, and advocacy groups, and serves as an association management system. CiviCRM is designed to manage information about an organisation's donors, members, event registrants, subscribers, grant application seekers and funders, and case contacts. Volunteers, activists, voters as well as more general sorts of business contacts such as employees, clients, or vendors can be managed using CiviCRM.</p>
        <p>CiviCRM's core tracks contacts, relationships, activities, groups, tags and permissions, while its components keep track of contributors (CiviContribute), events (CiviEvent), member lists (CiviMember), cases (CiviCase), grants (CiviGrant), campaigns (CiviCampaign), petitions (CiviPetition), bulk mailings (CiviMail) and reports (CiviReport).</p>
        <p>CiviCRM is deployed in conjunction with either the {'Drupal'|link_urls:'w'}, {'Joomla!'|link_urls:'w'} or {'WordPress'|link_urls:'w'} content management systems ({'CMS'|link_urls:'w'}), and is supported by many hosting and professional services companies. Both the Drupal and Joomla! professional associations use CiviCRM. CiviCRM's license is the GNU AGPL 3.</p>
        <p>CiviCRM version 4.2 supports Drupal 7, Joomla 2.5 and WordPress 3.3, with limited support for Drupal 6. There are a wide and growing number of integration modules with these CMSes to leverage their strengths. A large number of tokens are available for inclusion in {'HTML'|link_urls:'w'} or plaintext emails, or for producing {'PDF'|link_urls:'w'} files for printing. Data integration formats supported include {'RSS'|link_urls:'w'}, {'JSON'|link_urls:'w'}, {'XML'|link_urls:'w'}, and {'CSV'|link_urls:'w'}. Supported programming interfaces include REST, server {'PHP'|link_urls:'/l'} and client {'JavaScript'|link_urls:'/l'} APIs, a CMS-agnostic extensions framework and Drupal style hooks.</p>
        <p>CiviCRM is used by many large NGOs including <strong>Amnesty International</strong>, <strong>Creative Commons</strong>, the <strong>Free Software Foundation</strong>, and the <strong>Wikimedia Foundation</strong> for their fundraising. There are also cases of very large record sets being used with one company claiming to have set up CiviCRM with a set of over 3 million constituents. CiviCRM is also used by <strong>Kabissa</strong> to provide CRM capabilities to over 1,500 organisations, mostly in Africa.</p>
    </div>
</div>
