{{$smarty.template}|helper:'page':'registerTemplate':'it'}
{'ASCII Table'|helper:'page':'headline'}
<div class="row">
    <div class="col-lg-12 col-md-12">
        {$page->headline}
        <p>The <strong>American Standard Code for Information Interchange</strong> (<strong>ASCII</strong>) is a character-encoding scheme originally based on the English alphabet that encodes 128 specified characters - the numbers 0-9, the letters a-z and A-Z, some basic punctuation symbols, some control codes that originated with Teletype machines, and a blank space - into the 7-bit binary integers.</p>
        <table class="table table-bordered table-hover table-striped">
           <tr>
<th>Dec</th><th>Oct</th><th>Hex</th><th>char</th>
<td rowspan="33"></td>
<th>Dec</th><th>Oct</th><th>Hex</th><th>Char</th>
<td rowspan="33"></td>
<th>Dec</th><th>Oct</th><th>Hex</th><th>Char</th>
<td rowspan="33"></td>
<th>Dec</th><th>Oct</th><th>Hex</th><th>Char</th>
</tr>
<tr>
<td>0</td>
<td>0</td>
<td>00</td>
<td><b>NUL</b> (null)</td>
<td>32</td>
<td>40</td>
<td>20</td>
<td> (space)</td>
<td>64</td>
<td>100</td>
<td>40</td>
<td><b>@</b></td>
<td>96</td>
<td>140</td>
<td>60</td>
<td><b>`</b></td>
</tr>
<tr>
<td>1</td>
<td>1</td>
<td>01</td>
<td><b>SOH</b> (start of header)</td>
<td>33</td>
<td>41</td>
<td>21</td>
<td><b>!</b></td>
<td>65</td>
<td>101</td>
<td>41</td>
<td><b>A</b></td>
<td> 97</td>
<td>141</td>
<td>61</td>
<td><b>a</b>
</td></tr>
<tr>
<td> 2</td>
<td>2</td>
<td>02</td>
<td><b>STX</b> (start of text)</td>
<td>34</td>
<td>42</td>
<td>22</td>
<td><b>"</b></td>
<td>66</td>
<td>102</td>
<td>42</td>
<td><b>B</b></td>
<td> 98</td>
<td>142</td>
<td>62</td>
<td><b>b</b>
</td></tr>
<tr>
<td> 3</td>
<td>3</td>
<td>03</td>
<td><b>ETX</b> (end of text)</td>
<td>35</td>
<td>43</td>
<td>23</td>
<td><b>#</b></td>
<td>67</td>
<td>103</td>
<td>43</td>
<td><b>C</b></td>
<td> 99</td>
<td>143</td>
<td>63</td>
<td><b>c</b>
</td></tr>
<tr>
<td> 4</td>
<td>4</td>
<td>04</td>
<td><b>EOT</b> (end of transmission)</td>
<td>36</td>
<td>44</td>
<td>24</td>
<td><b>$</b></td>
<td>68</td>
<td>104</td>
<td>44</td>
<td><b>D</b></td>
<td>100</td>
<td>144</td>
<td>64</td>
<td><b>d</b>
</td></tr>
<tr>
<td> 5</td>
<td>5</td>
<td>05</td>
<td><b>ENQ</b> (enquiry)</td>
<td>37</td>
<td>45</td>
<td>25</td>
<td><b>%</b></td>
<td>69</td>
<td>105</td>
<td>45</td>
<td><b>E</b></td>
<td>101</td>
<td>145</td>
<td>65</td>
<td><b>e</b>
</td></tr>
<tr>
<td> 6</td>
<td>6</td>
<td>06</td>
<td><b>ACK</b> (acknowledge)</td>
<td>38</td>
<td>46</td>
<td>26</td>
<td><b>&amp;</b></td>
<td>70</td>
<td>106</td>
<td>46</td>
<td><b>F</b></td>
<td>102</td>
<td>146</td>
<td>66</td>
<td><b>f</b>
</td></tr>
<tr>
<td> 7</td>
<td>7</td>
<td>07</td>
<td><b>BEL</b> (bell)</td>
<td>39</td>
<td>47</td>
<td>27</td>
<td><b>'</b></td>
<td>71</td>
<td>107</td>
<td>47</td>
<td><b>G</b></td>
<td>103</td>
<td>147</td>
<td>67</td>
<td><b>g</b>
</td></tr>
<tr>
<td> 8</td>
<td>10</td>
<td>08</td>
<td><b>BS</b> (backspace)</td>
<td>40</td>
<td>50</td>
<td>28</td>
<td><b>(</b></td>
<td>72</td>
<td>110</td>
<td>48</td>
<td><b>H</b></td>
<td>104</td>
<td>150</td>
<td>68</td>
<td><b>h</b>
</td></tr>
<tr>
<td> 9</td>
<td>11</td>
<td>09</td>
<td><b>HT</b> (horizontal tab)</td>
<td>41</td>
<td>51</td>
<td>29</td>
<td><b>)</b></td>
<td>73</td>
<td>111</td>
<td>49</td>
<td><b>I</b></td>
<td>105</td>
<td>151</td>
<td>69</td>
<td><b>i</b>
</td></tr>
<tr>
<td>10</td>
<td>12</td>
<td>0a</td>
<td><b>LF</b> (line feed - new line)</td>
<td>42</td>
<td>52</td>
<td>2a</td>
<td><b>*</b></td>
<td>74</td>
<td>112</td>
<td>4a</td>
<td><b>J</b></td>
<td>106</td>
<td>152</td>
<td>6a</td>
<td><b>j</b>
</td></tr>
<tr>
<td>11</td>
<td>13</td>
<td>0b</td>
<td><b>VT</b> (vertical tab)</td>
<td>43</td>
<td>53</td>
<td>2b</td>
<td><b>+</b></td>
<td>75</td>
<td>113</td>
<td>4b</td>
<td><b>K</b></td>
<td>107</td>
<td>153</td>
<td>6b</td>
<td><b>k</b>
</td></tr>
<tr>
<td>12</td>
<td>14</td>
<td>0c</td>
<td><b>FF</b> (form feed - new page)</td>
<td>44</td>
<td>54</td>
<td>2c</td>
<td><b>,</b></td>
<td>76</td>
<td>114</td>
<td>4c</td>
<td><b>L</b></td>
<td>108</td>
<td>154</td>
<td>6c</td>
<td><b>l</b>
</td></tr>
<tr>
<td>13</td>
<td>15</td>
<td>0d</td>
<td><b>CR</b> (carriage return)</td>
<td>45</td>
<td>55</td>
<td>2d</td>
<td><b>-</b></td>
<td>77</td>
<td>115</td>
<td>4d</td>
<td><b>M</b></td>
<td>109</td>
<td>155</td>
<td>6d</td>
<td><b>m</b>
</td></tr>
<tr>
<td>14</td>
<td>16</td>
<td>0e</td>
<td><b>SO</b> (shift out)</td>
<td>46</td>
<td>56</td>
<td>2e</td>
<td><b>.</b></td>
<td>78</td>
<td>116</td>
<td>4e</td>
<td><b>N</b></td>
<td>110</td>
<td>156</td>
<td>6e</td>
<td><b>n</b>
</td></tr>
<tr>
<td>15</td>
<td>17</td>
<td>0f</td>
<td><b>SI</b> (shift in)</td>
<td>47</td>
<td>57</td>
<td>2f</td>
<td><b>/</b></td>
<td>79</td>
<td>117</td>
<td>4f</td>
<td><b>O</b></td>
<td>111</td>
<td>157</td>
<td>6f</td>
<td><b>o</b>
</td></tr>
<tr>
<td>16</td>
<td>20</td>
<td>10</td>
<td><b>DLE</b> (data link escape)</td>
<td>48</td>
<td>60</td>
<td>30</td>
<td><b>0</b></td>
<td>80</td>
<td>120</td>
<td>50</td>
<td><b>P</b></td>
<td>112</td>
<td>160</td>
<td>70</td>
<td><b>p</b>
</td></tr>
<tr>
<td>17</td>
<td>21</td>
<td>11</td>
<td><b>DC1</b> (device control 1)</td>
<td>49</td>
<td>61</td>
<td>31</td>
<td><b>1</b></td>
<td>81</td>
<td>121</td>
<td>51</td>
<td><b>Q</b></td>
<td>113</td>
<td>161</td>
<td>71</td>
<td><b>q</b>
</td></tr>
<tr>
<td>18</td>
<td>22</td>
<td>12</td>
<td><b>DC2</b> (device control 2)</td>
<td>50</td>
<td>62</td>
<td>32</td>
<td><b>2</b></td>
<td>82</td>
<td>122</td>
<td>52</td>
<td><b>R</b></td>
<td>114</td>
<td>162</td>
<td>72</td>
<td><b>r</b>
</td></tr>
<tr>
<td>19</td>
<td>23</td>
<td>13</td>
<td><b>DC3</b> (device control 3)</td>
<td>51</td>
<td>63</td>
<td>33</td>
<td><b>3</b></td>
<td>83</td>
<td>123</td>
<td>53</td>
<td><b>S</b></td>
<td>115</td>
<td>163</td>
<td>73</td>
<td><b>s</b>
</td></tr>
<tr>
<td>20</td>
<td>24</td>
<td>14</td>
<td><b>DC4</b> (device control 4)</td>
<td>52</td>
<td>64</td>
<td>34</td>
<td><b>4</b></td>
<td>84</td>
<td>124</td>
<td>54</td>
<td><b>T</b></td>
<td>116</td>
<td>164</td>
<td>74</td>
<td><b>t</b>
</td></tr>
<tr>
<td>21</td>
<td>25</td>
<td>15</td>
<td><b>NAK</b> (negative acknowledge)</td>
<td>53</td>
<td>65</td>
<td>35</td>
<td><b>5</b></td>
<td>85</td>
<td>125</td>
<td>55</td>
<td><b>U</b></td>
<td>117</td>
<td>165</td>
<td>75</td>
<td><b>u</b>
</td></tr>
<tr>
<td>22</td>
<td>26</td>
<td>16</td>
<td><b>SYN</b> (synchronous idle)</td>
<td>54</td>
<td>66</td>
<td>36</td>
<td><b>6</b></td>
<td>86</td>
<td>126</td>
<td>56</td>
<td><b>V</b></td>
<td>118</td>
<td>166</td>
<td>76</td>
<td><b>v</b>
</td></tr>
<tr>
<td>23</td>
<td>27</td>
<td>17</td>
<td><b>ETB</b> (end of transmission block)</td>
<td>55</td>
<td>67</td>
<td>37</td>
<td><b>7</b></td>
<td>87</td>
<td>127</td>
<td>57</td>
<td><b>W</b></td>
<td>119</td>
<td>167</td>
<td>77</td>
<td><b>w</b>
</td></tr>
<tr>
<td>24</td>
<td>30</td>
<td>18</td>
<td><b>CAN</b> (cancel)</td>
<td>56</td>
<td>70</td>
<td>38</td>
<td><b>8</b></td>
<td>88</td>
<td>130</td>
<td>58</td>
<td><b>X</b></td>
<td>120</td>
<td>170</td>
<td>78</td>
<td><b>x</b>
</td></tr>
<tr>
<td>25</td>
<td>31</td>
<td>19</td>
<td><b>EM</b> (end of medium)</td>
<td>57</td>
<td>71</td>
<td>39</td>
<td><b>9</b></td>
<td>89</td>
<td>131</td>
<td>59</td>
<td><b>Y</b></td>
<td>121</td>
<td>171</td>
<td>79</td>
<td><b>y</b>
</td></tr>
<tr>
<td>26</td>
<td>32</td>
<td>1a</td>
<td><b>SUB</b> (substitute)</td>
<td>58</td>
<td>72</td>
<td>3a</td>
<td><b>:</b></td>
<td>90</td>
<td>132</td>
<td>5a</td>
<td><b>Z</b></td>
<td>122</td>
<td>172</td>
<td>7a</td>
<td><b>z</b>
</td></tr>
<tr>
<td>27</td>
<td>33</td>
<td>1b</td>
<td><b>ESC</b> (escape)</td>
<td>59</td>
<td>73</td>
<td>3b</td>
<td><b>;</b></td>
<td>91</td>
<td>133</td>
<td>5b</td>
<td><b>[</b></td>
<td>123</td>
<td>173</td>
<td>7b</td>
<td><b>{literal}{{/literal}</b>
</td></tr>
<tr>
<td>28</td>
<td>34</td>
<td>1c</td>
<td><b>FS</b> (file separator)</td>
<td>60</td>
<td>74</td>
<td>3c</td>
<td><b>&lt;</b></td>
<td>92</td>
<td>134</td>
<td>5c</td>
<td><b>\ </b></td>
<td>124</td>
<td>174</td>
<td>7c</td>
<td><b>&#124;</b>
</td></tr>
<tr>
<td>29</td>
<td>35</td>
<td>1d</td>
<td><b>GS</b> (group separator)</td>
<td>61</td>
<td>75</td>
<td>3d</td>
<td><b>=</b></td>
<td>93</td>
<td>135</td>
<td>5d</td>
<td><b>]</b></td>
<td>125</td>
<td>175</td>
<td>7d</td>
<td><b>}</b>
</td></tr>
<tr>
<td>30</td>
<td>36</td>
<td>1e</td>
<td><b>RS</b> (record separator)</td>
<td>62</td>
<td>76</td>
<td>3e</td>
<td><b>&gt;</b></td>
<td>94</td>
<td>136</td>
<td>5e</td>
<td><b>^</b></td>
<td>126</td>
<td>176</td>
<td>7e</td>
<td><b>~</b>
</td></tr>
<tr>
<td>31</td>
<td>37</td>
<td>1f</td>
<td><b>US</b> (unit separator)</td>
<td>63</td>
<td>77</td>
<td>3f</td>
<td><b>?</b></td>
<td>95</td>
<td>137</td>
<td>5f</td>
<td><b>_</b></td>
<td>127</td>
<td>177</td>
<td>7f</td>
<td><b>DEL</b> (delete)</td>
</tr>
</table> 
    </div>
</div>
